services:
  server:
    build: ./server
    ports:
      - "8081:8081"
    environment:
      - HOST=0.0.0.0
      - PORT=8081
    volumes:
      - ../Notes/Hosted:/app/Notes/Hosted:ro

  client:
    build: 
      context: ./client/  
      args: 
        - VITE_SERVER_URL=http://localhost:8001
        - VITE_HOST=0.0.0.0
        - VITE_PORT=8080
    ports:
      - "8080:8080"
