services:
  server:
    build: ./server
    ports:
      - "8001:8001"
    environment:
      - HOST=localhost
      - PORT=8001

  client:
    build: 
      context: ./client/  
      args: 
        - VITE_SERVER_URL=http://localhost:8001
        - VITE_HOST=localhost
        - VITE_PORT=8080
    ports:
      - "8080:8080"
